import Groq from "groq-sdk";
import {
  ALLOWED_STYLES,
  DEFAULT_INTERPRETED_STYLE,
  type InterpretedStyle,
  type RevisionIntent,
} from "@/src/ai/types";
import type { StyleOption } from "@/src/music/types";
import type {
  ChordEditAction,
  HarmonyChordQuality,
} from "@/src/harmony/actions";

const MAX_PROMPT_LENGTH = 500;
const MAX_SUMMARY_LENGTH = 240;
const MAX_MOOD_ITEMS = 5;
const MAX_MOOD_LENGTH = 40;
const MAX_PROGRESSION_MEASURES = 8;
const MAX_SYMBOL_LENGTH = 40;
// The staff is a fixed four measures; chord-edit actions address measures 1-4.
const STAFF_MEASURE_COUNT = 4;
const MAX_ACTIONS = 8;
const ALLOWED_QUALITIES: HarmonyChordQuality[] = [
  "major",
  "minor",
  "dominant",
  "diminished",
];

type CurrentProgressionItem = { measure: number; romanNumeral: string };

type InterpretResponse = InterpretedStyle & {
  warning?: string;
  revision?: RevisionIntent;
  actions?: ChordEditAction[];
};

// Shared, appended to both prompts. Lets the model express EXACT chord requests
// as a small action list. It never returns chord pitch names — only scale
// degree + quality (+ optional 7th) + measure, which the engine resolves
// deterministically against the current key.
const ACTIONS_INSTRUCTIONS = `Exact chord edits ("actions"):
- Also return an "actions" array. Use it ONLY for chords the user explicitly names; otherwise return "actions": [].
- To set a specific chord at a measure, use scale degree (1-7) + quality:
  { "type": "set_chord", "measure": <1-4>, "degree": <1-7>, "quality": "major"|"minor"|"dominant"|"diminished", "extension": 7 }
  Omit "extension" for a plain triad; include "extension": 7 for a seventh chord.
- To make one measure's chord identical to another's (e.g. "make the first and last chord the same"), use:
  { "type": "copy_chord", "fromMeasure": <1-4>, "toMeasure": <1-4> }
- Roman-numeral mapping: degree 1 = i/I, ... degree 7. "imin7" = degree 1, quality "minor", extension 7. "ivmin7" = degree 4, quality "minor", extension 7. "Vdom7" = degree 5, quality "dominant", extension 7.
- Do NOT return chord pitch names or note letters in actions. Only type, measure, degree, quality, extension, fromMeasure, toMeasure.
- measure, degree, fromMeasure, and toMeasure are 1-based.`;

const SYSTEM_PROMPT = `You translate a musician's plain-English description of the harmony they want into a small JSON settings object. You do NOT compose music.

Rules:
- Return ONLY a JSON object. No prose, no markdown.
- "primaryStyle" must be exactly one of: "simple", "jazzy", "bluesy", "descendingBass". Use no other value.
- Do not return chord names. Do not generate a progression.
- Map simple / pop / clean / basic language toward "simple".
- Map jazz / lush / sophisticated / colorful language toward "jazzy".
- Map blues / gritty / dominant-seventh language toward "bluesy".
- Increase "descendingBassWeight" for falling, walking-down, or descending bass requests.
- Lower "dissonanceTolerance" for safe, smooth, or consonant requests.
- Raise "dissonanceTolerance" for tense, surprising, or experimental requests.
- Raise "cadenceStrength" for resolved, satisfying, or strong-ending requests.

All numeric fields are between 0 and 1. Respond with exactly this shape:
{
  "primaryStyle": "simple",
  "descendingBassWeight": 0.0,
  "complexity": 0.0,
  "dissonanceTolerance": 0.0,
  "cadenceStrength": 0.0,
  "preferSevenths": false,
  "preferSuspensions": false,
  "mood": [],
  "summary": "",
  "actions": []
}

${ACTIONS_INSTRUCTIONS}`;

const REVISION_SYSTEM_PROMPT = `You translate a musician's request to MODIFY an existing chord progression into a small JSON settings object. The progression was generated by a separate engine. You do NOT compose, choose, or rename chords.

You are given the current progression (measure numbers with Roman-numeral chord names) and the user's instruction.

Rules:
- Return ONLY a JSON object. No prose, no markdown.
- "primaryStyle" must be exactly one of: "simple", "jazzy", "bluesy", "descendingBass".
- Do not return chord names. Do not generate or rename chords.
- "revision.preserveOverallProgression": true to keep the same general progression, false to allow broad replacement.
- "revision.preserveChordPositions": array of measure numbers the user explicitly wants kept the same (e.g. "keep the first two chords" -> [1, 2]). Empty if none.
- "revision.changeAmount": 0 for a tiny tweak, 0.5 for moderate, 1 for a large change.
- "revision.requestedChanges": numeric deltas in [-1, 1]. Positive means more, negative means less. Omit or use 0 when not requested:
  - "complexityDelta": "more complex / richer / add color" positive; "simpler" negative.
  - "dissonanceDelta": "more tense / dissonant" positive; "smoother / less dissonant" negative.
  - "descendingBassDelta": "make the bass descend more" positive.
  - "cadenceDelta": "stronger / more resolved ending" positive.

Respond with exactly this shape:
{
  "primaryStyle": "simple",
  "descendingBassWeight": 0.0,
  "complexity": 0.0,
  "dissonanceTolerance": 0.0,
  "cadenceStrength": 0.0,
  "preferSevenths": false,
  "preferSuspensions": false,
  "mood": [],
  "summary": "",
  "revision": {
    "preserveOverallProgression": true,
    "preserveChordPositions": [],
    "changeAmount": 0.3,
    "requestedChanges": {
      "complexityDelta": 0.0,
      "dissonanceDelta": 0.0,
      "descendingBassDelta": 0.0,
      "cadenceDelta": 0.0
    }
  },
  "actions": []
}

${ACTIONS_INSTRUCTIONS}`;

function clamp01(value: unknown, fallback: number): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return fallback;
  return Math.min(1, Math.max(0, value));
}

function clampDelta(value: unknown): number | undefined {
  if (typeof value !== "number" || !Number.isFinite(value)) return undefined;
  return Math.min(1, Math.max(-1, value));
}

function sanitizeCurrentProgression(value: unknown): CurrentProgressionItem[] {
  if (!Array.isArray(value)) return [];
  return value.slice(0, MAX_PROGRESSION_MEASURES).flatMap((raw) => {
    const item = (raw ?? {}) as Record<string, unknown>;
    const measure = item.measure;
    const romanNumeral =
      typeof item.romanNumeral === "string"
        ? item.romanNumeral.trim().slice(0, MAX_SYMBOL_LENGTH)
        : "";
    if (typeof measure !== "number" || !Number.isFinite(measure) || !romanNumeral) {
      return [];
    }
    return [{ measure, romanNumeral }];
  });
}

function sanitizeRevision(raw: unknown, measureCount: number): RevisionIntent {
  const data = (raw ?? {}) as Record<string, unknown>;

  const preserveChordPositions = Array.isArray(data.preserveChordPositions)
    ? Array.from(
        new Set(
          data.preserveChordPositions.filter(
            (n): n is number =>
              typeof n === "number" &&
              Number.isInteger(n) &&
              n >= 1 &&
              n <= measureCount
          )
        )
      )
    : [];

  const requested = (data.requestedChanges ?? {}) as Record<string, unknown>;
  const requestedChanges: RevisionIntent["requestedChanges"] = {};
  const complexityDelta = clampDelta(requested.complexityDelta);
  const dissonanceDelta = clampDelta(requested.dissonanceDelta);
  const descendingBassDelta = clampDelta(requested.descendingBassDelta);
  const cadenceDelta = clampDelta(requested.cadenceDelta);
  if (complexityDelta !== undefined) requestedChanges.complexityDelta = complexityDelta;
  if (dissonanceDelta !== undefined) requestedChanges.dissonanceDelta = dissonanceDelta;
  if (descendingBassDelta !== undefined)
    requestedChanges.descendingBassDelta = descendingBassDelta;
  if (cadenceDelta !== undefined) requestedChanges.cadenceDelta = cadenceDelta;

  return {
    preserveOverallProgression:
      typeof data.preserveOverallProgression === "boolean"
        ? data.preserveOverallProgression
        : true,
    preserveChordPositions,
    changeAmount: clamp01(data.changeAmount, 0.3),
    requestedChanges,
  };
}

function isIntInRange(value: unknown, min: number, max: number): value is number {
  return (
    typeof value === "number" &&
    Number.isInteger(value) &&
    value >= min &&
    value <= max
  );
}

// Validates the model's exact-edit actions into a clean, typed list. Each action
// is rebuilt from known fields only (so unknown fields are dropped), and any
// action that fails validation or has an unknown type is skipped rather than
// passed through. Never fabricates an action the model did not return.
function sanitizeActions(value: unknown): ChordEditAction[] {
  if (!Array.isArray(value)) return [];

  const actions: ChordEditAction[] = [];

  for (const raw of value.slice(0, MAX_ACTIONS)) {
    const item = (raw ?? {}) as Record<string, unknown>;

    if (item.type === "set_chord") {
      if (!isIntInRange(item.measure, 1, STAFF_MEASURE_COUNT)) continue;
      if (!isIntInRange(item.degree, 1, 7)) continue;
      if (
        typeof item.quality !== "string" ||
        !ALLOWED_QUALITIES.includes(item.quality as HarmonyChordQuality)
      ) {
        continue;
      }
      // extension may only be omitted/null or exactly 7.
      let extension: 7 | undefined;
      if (item.extension === undefined || item.extension === null) {
        extension = undefined;
      } else if (item.extension === 7) {
        extension = 7;
      } else {
        continue;
      }

      actions.push({
        type: "set_chord",
        measure: item.measure,
        degree: item.degree,
        quality: item.quality as HarmonyChordQuality,
        ...(extension === 7 ? { extension } : {}),
      });
    } else if (item.type === "copy_chord") {
      if (!isIntInRange(item.fromMeasure, 1, STAFF_MEASURE_COUNT)) continue;
      if (!isIntInRange(item.toMeasure, 1, STAFF_MEASURE_COUNT)) continue;
      if (item.fromMeasure === item.toMeasure) continue;

      actions.push({
        type: "copy_chord",
        fromMeasure: item.fromMeasure,
        toMeasure: item.toMeasure,
      });
    }
    // Unknown action types are ignored.
  }

  return actions;
}

function asBoolean(value: unknown, fallback: boolean): boolean {
  return typeof value === "boolean" ? value : fallback;
}

function asStyle(value: unknown): StyleOption {
  return ALLOWED_STYLES.includes(value as StyleOption)
    ? (value as StyleOption)
    : DEFAULT_INTERPRETED_STYLE.primaryStyle;
}

function asMood(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim().slice(0, MAX_MOOD_LENGTH))
    .filter((item) => item.length > 0)
    .slice(0, MAX_MOOD_ITEMS);
}

function asSummary(value: unknown): string {
  if (typeof value !== "string") return DEFAULT_INTERPRETED_STYLE.summary;
  const trimmed = value.trim();
  if (trimmed.length === 0) return DEFAULT_INTERPRETED_STYLE.summary;
  return trimmed.slice(0, MAX_SUMMARY_LENGTH);
}

// Coerce an arbitrary parsed object into a safe InterpretedStyle, substituting
// defaults for anything missing or out of range.
function sanitizeInterpretation(raw: unknown): InterpretedStyle {
  const data = (raw ?? {}) as Record<string, unknown>;
  return {
    primaryStyle: asStyle(data.primaryStyle),
    descendingBassWeight: clamp01(
      data.descendingBassWeight,
      DEFAULT_INTERPRETED_STYLE.descendingBassWeight,
    ),
    complexity: clamp01(data.complexity, DEFAULT_INTERPRETED_STYLE.complexity),
    dissonanceTolerance: clamp01(
      data.dissonanceTolerance,
      DEFAULT_INTERPRETED_STYLE.dissonanceTolerance,
    ),
    cadenceStrength: clamp01(
      data.cadenceStrength,
      DEFAULT_INTERPRETED_STYLE.cadenceStrength,
    ),
    preferSevenths: asBoolean(
      data.preferSevenths,
      DEFAULT_INTERPRETED_STYLE.preferSevenths,
    ),
    preferSuspensions: asBoolean(
      data.preferSuspensions,
      DEFAULT_INTERPRETED_STYLE.preferSuspensions,
    ),
    mood: asMood(data.mood),
    summary: asSummary(data.summary),
  };
}

function json(body: InterpretResponse, status = 200): Response {
  return Response.json(body, { status });
}

export async function POST(request: Request): Promise<Response> {
  let prompt = "";
  let currentProgression: CurrentProgressionItem[] = [];
  let isRevision = false;

  try {
    const body = (await request.json()) as {
      prompt?: unknown;
      hasProgression?: unknown;
      currentProgression?: unknown;
    };
    prompt = typeof body?.prompt === "string" ? body.prompt.trim() : "";
    currentProgression = sanitizeCurrentProgression(body?.currentProgression);
    isRevision = body?.hasProgression === true && currentProgression.length > 0;
  } catch {
    // Malformed JSON body: fall back to safe defaults rather than throwing.
    return json({ ...DEFAULT_INTERPRETED_STYLE });
  }

  // Empty prompt: deterministic defaults, no Groq call.
  if (prompt.length === 0) {
    return json({ ...DEFAULT_INTERPRETED_STYLE });
  }

  // Reject overly long prompts, but keep a usable response shape.
  if (prompt.length > MAX_PROMPT_LENGTH) {
    return json(
      {
        ...DEFAULT_INTERPRETED_STYLE,
        warning: `Prompt exceeds ${MAX_PROMPT_LENGTH} characters; using default style.`,
      },
      400,
    );
  }

  if (!process.env.GROQ_API_KEY) {
    console.error("interpret-style: GROQ_API_KEY is not configured.");
    return json({
      ...DEFAULT_INTERPRETED_STYLE,
      warning: "AI interpretation is not configured; using default style.",
    });
  }

  const model = process.env.GROQ_MODEL ?? "llama-3.1-8b-instant";

  try {
    const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

    // In revision mode the model also fills a "revision" object and is shown the
    // current progression. Otherwise it only interprets the style.
    const systemPrompt = isRevision ? REVISION_SYSTEM_PROMPT : SYSTEM_PROMPT;
    const userContent = isRevision
      ? JSON.stringify({ instruction: prompt, currentProgression })
      : prompt;

    const completion = await groq.chat.completions.create({
      model,
      temperature: 0,
      max_completion_tokens: isRevision ? 400 : 300,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userContent },
      ],
    });

    const content = completion.choices[0]?.message?.content;
    if (!content) {
      return json({
        ...DEFAULT_INTERPRETED_STYLE,
        warning: "AI interpretation was empty; using default style.",
      });
    }

    const parsed = JSON.parse(content) as {
      revision?: unknown;
      actions?: unknown;
    };
    const interpretation = sanitizeInterpretation(parsed);
    const actions = sanitizeActions(parsed.actions);

    if (isRevision) {
      return json({
        ...interpretation,
        revision: sanitizeRevision(parsed.revision, currentProgression.length),
        actions,
      });
    }

    return json({ ...interpretation, actions });
  } catch (error) {
    // Log server-side only; never leak the key or a stack trace to the client.
    console.error(
      "interpret-style: Groq request failed:",
      error instanceof Error ? error.message : "unknown error",
    );
    return json({
      ...DEFAULT_INTERPRETED_STYLE,
      warning: "AI interpretation was unavailable; using default style.",
    });
  }
}
